#!/bin/sh
# export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib

# Ensure the connection string is correctly formatted
sqlplus64 "akuganen/02152297@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.torontomu.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
INSERT INTO STADIUM (STADIUMID, STADIUMNAME, AREA, SEATS)
    VALUES ('00', 'Free-Agency', 'N/A', 0);
INSERT INTO STADIUM (STADIUMID, STADIUMNAME, AREA, SEATS)
    VALUES ('01', 'BMO Field', 'Toronto, ON', 40000);
INSERT INTO STADIUM (STADIUMID, STADIUMNAME, AREA, SEATS)
    VALUES ('02', 'Stade Olympique', 'Montreal, QC', 61004);
INSERT INTO STADIUM (STADIUMID, STADIUMNAME, AREA, SEATS)
    VALUES ('03', 'Commonwealth Stadium', 'Edmonton, AB', 56302);
INSERT INTO STADIUM (STADIUMID, STADIUMNAME, AREA, SEATS)
    VALUES ('04', 'BC Place', 'Vancouver, BC', 54320);
INSERT INTO STADIUM (STADIUMID, STADIUMNAME, AREA, SEATS)
    VALUES ('05', 'McMahon Stadium', 'Calgary, AB', 37317);

INSERT INTO TEAM (TEAMID, TEAMNAME, STADIUMID)
    VALUES ('FA', 'Free-Agents', '00');
INSERT INTO TEAM (TEAMID, TEAMNAME, STADIUMID)
    VALUES ('01', 'Toronto FC', '01');
INSERT INTO TEAM (TEAMID, TEAMNAME, STADIUMID)
    VALUES ('02', 'Strikers United', '02');
INSERT INTO TEAM (TEAMID, TEAMNAME, STADIUMID)
    VALUES ('03', 'Phoenix FC', '03');
INSERT INTO TEAM (TEAMID, TEAMNAME, STADIUMID)
    VALUES ('04', 'Red Raptors FC', '04');

INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('01', 'Lionel Messi', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('02', 'Cristiano Ronaldo', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('03', 'Kylian Mbappe', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('04', 'Kevin De Bruyne', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('05', 'Virgil van Dijk', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('06', 'Mohamed Salah', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('07', 'Sergio Ramos', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('08', 'Robert Lewandowski', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('09', 'Neymar Jr', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('10', 'Luka Modric', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('11', 'Erling Haaland', '01');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('12', 'Karim Benzema', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('13', 'Harry Kane', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('14', 'Paul Pogba', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('15', 'Toni Kroos', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('16', 'Romelu Lukaku', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('17', 'Jadon Sancho', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('18', 'Gareth Bale', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('19', 'Eden Hazard', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('20', 'Alisson Becker', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('21', 'Gerard Pique', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('22', 'Thiago Silva', '02');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('23', 'Luis Suarez', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('24', 'Raheem Sterling', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('25', 'Phil Foden', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('26', 'Joshua Kimmich', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('27', 'Manuel Neuer', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('28', 'Leroy Sane', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('29', 'Riyad Mahrez', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('30', 'Pierre-Emerick Aubameyang', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('31', 'Aymeric Laporte', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('32', 'Andrew Robertson', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('33', 'Pele', '03');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('34', 'Bruno Fernandes', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('35', 'Joao Felix', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('36', 'Sadio Mane', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('37', 'Trent Alexander-Arnold', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('38', 'Marcus Rashford', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('39', 'Mason Mount', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('40', 'Declan Rice', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('41', 'Diego Maradona', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('42', 'Kalidou Koulibaly', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('43', 'Paulo Dybala', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME, TEAMID)
    VALUES ('44', 'Zlatan Ibrahimovic', '04');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME)
    VALUES ('45', 'Kyrie Irving');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME)
    VALUES ('46', 'Kanye West');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME)
    VALUES ('47', 'Quandale Dingle');
INSERT INTO PLAYER (PLAYERID, PLAYERNAME)
    VALUES ('48', 'P Diddy');

INSERT INTO COACH (COACHNAME, TEAMID)
    VALUES ('J.Mourinho', '01');
INSERT INTO COACH (COACHNAME, TEAMID)
    VALUES ('E.Kamalachandran', '04');
INSERT INTO COACH (COACHNAME, TEAMID)
    VALUES ('H.BOB', '02');
INSERT INTO COACH (COACHNAME, TEAMID)
    VALUES ('J.JOE', '03');

INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('01', '01', '02', 3, 0, '01', 36232, TO_DATE('2024-10-12', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('02', '03', '04', 1, 2, '03', 46732, TO_DATE('2024-10-13', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('03', '02', '03', 2, 2, '02', 54337, TO_DATE('2024-10-19', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('04', '04', '01', 0, 1, '04', 37234, TO_DATE('2024-10-20', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('05', '01', '03', 0, 0, '01', 38765, TO_DATE('2024-10-26', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE) 
    VALUES ('06', '02', '04', 1, 0, '02', 57283, TO_DATE('2024-10-27', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('07', '03', '01', 2, 3, '03', 52352, TO_DATE('2024-11-02', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('08', '04', '02', 1, 0, '04', 35627, TO_DATE('2024-11-03', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('09', '03', '02', 1, 2, '03', 41738, TO_DATE('2024-11-09', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('10', '01', '04', 0, 2, '01', 39875, TO_DATE('2024-11-10', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('11', '02', '01', 1, 2, '02', 60125, TO_DATE('2024-11-16', 'YYYY-MM-DD'));
INSERT INTO GAME (GAMEID, HOMETEAM, AWAYTEAM, HOMEGOALS, AWAYGOALS, STADIUMID, ATTENDANCE, GAMEDATE)
    VALUES ('12', '04', '03', 1, 0, '04', 36783, TO_DATE('2024-11-17', 'YYYY-MM-DD'));


-- Populating GOAL table
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('01', '01', '04', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('01', '01', '03', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('01', '02', '01', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('02', '23', '24', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('02', '35', '34', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('02', '36', '37', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('03', '12', '14', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('03', '13', '15', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('03', '23', '25', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('03', '28', '26', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('04', '01', '04', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('06', '19', '14', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('07', '30', '29', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('07', '30', '25', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('07', '01', '06', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('07', '01', '09', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('07', '02', '01', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('08', '44', '40', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('09', '13', '17', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('09', '18', '15', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('09', '23', '32', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('10', '43', '41', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('10', '35', '34', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('11', '12', '14', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('11', '11', '01', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('11', '02', '01', 'G');
INSERT INTO GOAL (GAMEID, SCORER, ASSISTER, GOALTYPE)
    VALUES ('12', '34', '35', 'G');

INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('01', '3-0', '01');
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('02', '1-2', '04');
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('03', '2-2', NULL);
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('04', '0-1', '01');
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('05', '0-0', NULL);
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('06', '1-0', '02');
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('07', '2-3', '01');
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('08', '1-0', '04');
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('09', '1-2', '02');
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('10', '0-2', '04');
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('11', '1-2', '01');
INSERT INTO SCORE (GAMEID, SCORE, WINNER)
    VALUES ('12', '1-0', '04');

UPDATE PLAYER
SET GAMES = 6
WHERE TEAMID != 'FA';

UPDATE PLAYER
SET GOALS = (
    SELECT COUNT(*) -- all occurrences 
    FROM GOAL
    WHERE playerid = scorer
);

UPDATE PLAYER
SET ASSISTS = (
    SELECT COUNT(*)
    FROM GOAL
    WHERE playerid = assister
);

UPDATE STADIUM s
SET AVGATTENDANCE = (
    SELECT ROUND(AVG(m.attendance), 2)
    FROM GAME m
    WHERE m.stadiumid = s.stadiumid
    GROUP BY m.stadiumid
);

exit;
EOF